apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress
  namespace: default
spec:
  mode: all
  selector:
    labelSelectors:
      app: hello-node
  stressors:
    memory:
      workers: 1
      size: "500MB"
  duration: "30s"