apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
  namespace: default
spec:
  action: pod-kill        
  mode: one                 
  selector:
    labelSelectors:
      app: hello-node       
  duration: "10s"          
